/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb95f',
        'secondary-fixed-dim': '#6bd8cb',
        'tertiary': '#000000',
        'surface-container-low': '#f3f4f3',
        'tertiary-fixed': '#ffddb8',
        'on-primary-container': '#778598',
        'on-secondary-fixed-variant': '#005049',
        'secondary': '#006a61',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#bac8dc',
        'on-tertiary-container': '#b87500',
        'on-secondary-container': '#006f66',
        'on-primary-fixed-variant': '#3a4859',
        'primary-fixed': '#d6e4f9',
        'on-secondary': '#ffffff',
        'background': '#f9f9f8',
        'on-primary': '#ffffff',
        'outline-variant': '#c4c6cc',
        'surface-tint': '#525f71',
        'on-tertiary-fixed-variant': '#653e00',
        'on-tertiary': '#ffffff',
        'on-surface': '#1a1c1c',
        'surface-bright': '#f9f9f8',
        'on-surface-variant': '#44474c',
        'secondary-container': '#86f2e4',
        'surface-container-high': '#e8e8e7',
        'on-error': '#ffffff',
        'inverse-surface': '#2f3130',
        'surface-container': '#eeeeed',
        'on-primary-fixed': '#0f1c2c',
        'surface': '#f9f9f8',
        'primary-fixed-dim': '#bac8dc',
        'surface-dim': '#dadad9',
        'tertiary-container': '#2a1700',
        'surface-container-highest': '#e2e2e2',
        'outline': '#74777d',
        'error-container': '#ffdad6',
        'primary': '#000000',
        'on-background': '#1a1c1c',
        'surface-variant': '#e2e2e2',
        'on-secondary-fixed': '#00201d',
        'primary-container': '#0f1c2c',
        'on-tertiary-fixed': '#2a1700',
        'inverse-on-surface': '#f1f1f0',
        'error': '#ba1a1a',
        'secondary-fixed': '#89f5e7',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
      },
      spacing: {
        'unit': '4px',
        'margin-mobile': '20px',
        'stack-lg': '24px',
        'gutter': '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
      },
    },
  },
  plugins: [],
}
