import { ArrowLeft, CheckCircle2, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useSeo } from '../hooks/useSeo';

const SITE_URL = 'https://drivehours.app';

export function DmvDrivingHoursVerificationGuide() {
  useSeo({ title: 'Does the DMV Check Your Driving Hours? | DriveHours', description: 'Understand how to prepare a clear supervised-practice record, when signatures or affidavits may be needed, and why you should check your state’s rules.', canonicalUrl: `${SITE_URL}/does-dmv-check-driving-hours` });
  const breadcrumbSchema = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'DriveHours', item: `${SITE_URL}/` }, { '@type': 'ListItem', position: 2, name: 'Does the DMV Check Driving Hours?', item: `${SITE_URL}/does-dmv-check-driving-hours` }] };
  return <article className="max-w-3xl mx-auto space-y-6 animate-fade-in">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
    <nav aria-label="Breadcrumb" className="flex items-center gap-1.5 text-xs"><Link to="/" className="text-teal-700 dark:text-teal-400 font-semibold hover:underline inline-flex items-center gap-1"><ArrowLeft className="w-3.5 h-3.5" /> DriveHours</Link><span className="text-slate-400">/</span><span className="text-slate-500">Driving-hour records</span></nav>
    <header className="space-y-3"><div className="flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-teal-600" /><span className="text-xs font-bold uppercase tracking-wider text-slate-500">Licensing preparation</span></div><h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-900 dark:text-white">Does the DMV Check Your Driving Hours?</h1><p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">Documentation and review requirements vary by state. The safest approach is to keep a complete supervised-practice record, follow your state’s form and signature rules, and bring the items your licensing agency requests.</p></header>
    <aside className="rounded-2xl border border-teal-200 bg-teal-50 p-4 text-sm text-slate-700 dark:border-teal-900/70 dark:bg-teal-950/30 dark:text-slate-200"><strong>Check before your appointment:</strong> DriveHours organizes your log, but your state licensing agency decides what record or certification it requires.</aside>
    <section className="app-card p-5 space-y-3"><h2 className="text-lg font-bold text-slate-900 dark:text-white">Prepare a clear record</h2><ul className="space-y-2 text-sm text-slate-600 dark:text-slate-300">{['Use the current form or format your state accepts','Record each supervised drive consistently','Keep required adult signatures or certifications with the log','Compare your totals with the state requirement before you schedule','Bring the documents named in your state’s road-test instructions'].map(item => <li key={item} className="flex gap-2"><CheckCircle2 className="w-4 h-4 text-teal-600 mt-0.5 flex-shrink-0" />{item}</li>)}</ul></section>
    <section className="app-card p-5 space-y-3"><h2 className="text-lg font-bold text-slate-900 dark:text-white">Use your state guide for the details</h2><p className="text-sm text-slate-600 dark:text-slate-300">Requirements can change and are not the same everywhere. Select your state to see the current local target and official-source link, then use the national guides to keep your practice organized.</p><div className="flex flex-col gap-2 text-sm font-semibold"><Link to="/dmv" className="text-teal-700 hover:underline dark:text-teal-300">Browse state driving-log requirements</Link><Link to="/50-hour-driving-log" className="text-teal-700 hover:underline dark:text-teal-300">Learn what to include in a 50-hour driving log</Link><Link to="/night-driving-hours" className="text-teal-700 hover:underline dark:text-teal-300">Understand state-specific night driving hours</Link></div></section>
    <section className="app-card p-6 text-center space-y-3"><h2 className="text-lg font-bold text-slate-900 dark:text-white">Keep every practice drive in one place</h2><p className="text-sm text-slate-600 dark:text-slate-300">Track supervised sessions offline and export a clear record when you are ready.</p><Link to="/" className="inline-flex min-h-16 items-center justify-center rounded-2xl bg-teal-600 px-8 text-sm font-bold text-white shadow-teal hover:bg-teal-700">Start Logging for Free</Link></section>
  </article>;
}
